### PR TITLE
Trajectory weights

### PR DESCRIPTION
**Pull request by fnueske**
Enables time-dependent weights in the computation of correlations. Weights can be given as integers for every trajectory or as ndarray for each time step. The weights parameter defaults to "None" for the standard case.

Also, the RunningCovar estimator now possesses a "time-lagged"-flag and an optional lag-time parameter. If these are activated, a single array can be fed into add() and it is automatically decomposed into the time-lagged parts.

Tests have been updated to treat all possible cases. An old test (/estimators/tests/TestData.npz + /estimators/tests/TestEstimator.py) has been removed.

Updating formulas for chunkwise estimation are described in /docs/UpdatingFormulas.pdf.

### CODE REVIEW

**Comment by fnueske** [comment]
@franknoe , did you have a chance to look at this?

**Comment by franknoe** [comment]
sorry, I'm behind on this. Will do it asap.

Am 03/06/16 um 09:52 schrieb Feliks Nüske:

> @franknoe https://github.com/franknoe , did you have a chance to 
> look at this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/variational/pull/32#issuecomment-223514276, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQiU_VtQoMcexwrUIDuCJXDUj-V9Rks5qH91AgaJpZM4IjTZu.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
@fnueske : thanks a lot, this looks all good to me. For some reason the AppVeyor test didn't execute. ls check with @marscher and once this is fixed the PR can be merged.

**Comment by marscher** [comment]
I resolved the merge-conflicts.

**Comment by fnueske** [comment]
Thanks!

**Pull request merged**
