### PR TITLE
debugged ramachandran.py

### PR DESCRIPTION
**Pull request by fvitalini**

### CODE REVIEW

**Comment by fvitalini** [comment]
I have tested ramachandran.py and it reproduces the results I had with my previous script. If anyone finds bugs, please let me know.

Francesca

**Comment by franknoe** [comment]
I think you have a problem with tabs. In python every tab should be exactly 4 spaces. Otherwise it becomes a mess. Can you use an editor which ensures 4 space when you press tab? 

I am using PyCharm that I like a lot, but it's a matter of taste

**Comment by fvitalini** [comment]
I use vi (yes i l know i should upgrade)and there the tab is more than 4
spaces , but I can check with some editor.

Francesca

Francesca
Il 30/lug/2015 01:03 "Frank Noe" notifications@github.com ha scritto:

**Comment by ppxasjsm** [comment]
You can also change the tabspacing of vi, but python shouldn't be tabs really but all spaces. 
Atom is good for linux, and it removes all trailing whitespaces. Though PyCharm is great for python stuff!!

For vi, you can put this into your .vimrc:

```
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
```

But consider switching to pycharm/atom.

**Comment by trendelkampschroer** [comment]
http://www.vim.org/scripts/script.php?script_id=3770

or 

:-)

https://www.gnu.org/software/emacs/emacs.html#Obtaining

**Comment by franknoe** [comment]
Besides the tab-issue, which is trivial, pyCharm and some other editors 
automatically check python code while writing it. I would really like to 
ask everyone to use one of these more clever programs, because it's not 
necessarily my job to remove simple syntax errors in untested code 
fragments when that could be done automatically.

Am 30/07/15 um 12:15 schrieb ppxasjsm:

> You can also change the tabspacing of vi, but python shouldn't be tabs 
> really but all spaces.
> Atom is good for linux, and it removes all trailing whitespaces. 
> Though PyCharm is great for python stuff!!
> 
> For vi, you can put this into your .vimrc:
> 
> |filetype plugin indent on
> set tabstop=4
> set shiftwidth=4
> set expandtab
> |
> 
> But consider switching to pycharm/atom.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/pull/4#issuecomment-126261310.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
