### PR TITLE
Covar improved merge

### PR DESCRIPTION
**Pull request by franknoe**
This PR provides a first operation-ready version of efficient moment and covariance calculation.
- First API definition in variational.estimators.
- Small performance improvements.
- Better documentation.
- Extensive Benchmarking
- Extensive Tests for moment computation and running moment computation

### CODE REVIEW

**Comment by franknoe** [comment]
Ready for review and merge @fnueske

**Comment by fnueske** [comment]
Hey @franknoe , just one small error: In variational/estimators/moments.py/_M2 and .../_M2_symmetric:
The second condition must be
elif _is_zero(xsum) and _is_zero(**ysum**) ...
Everything else is fine.

**Comment by franknoe** [comment]
Thank you very much. Will merge once the tests are done.

**Comment by franknoe** [comment]
Done. @fnueske , this is ready to use.

**Pull request merged**
