### PR TITLE
Add basisset vitalini

### PR DESCRIPTION
**Pull request by fvitalini**

### CODE REVIEW

**Comment by franknoe** [comment]
Wow, pretty good. And a real PR! Thanks a lot Francesca!

There are a few minor issues with the formatting and the spelling, but we can work on these afterwards. I am going to merge this.

**Comment by fvitalini** [comment]
@ Frank:
- psi /phi time series should be in degrees or radiants?
- at the current status we treat the input files as bumpy array of shape (T, X) with T = number of time steps and X= 2*number of residues. Shouldn't this lead us to memory issues?  
- I have sent you a pull request to add my commits (that I created to branch in a fork at my name).
  Feliks instead had previously created a branch directly from the original repository. What do you prefer and can you check if the two of us have all the correct permissions?

General question: how do we treat errors?

**Comment by fvitalini** [comment]
Thanks Frank for the comment. Feliks and I have been working on it this afternoon. Can this be considered sufficient as an answer to the reviewer so that we deal with these minor issues later? Of course it will still need to be tested.

**Comment by franknoe** [comment]
We should definitely test it before sending the revision.

Am 28/07/15 um 17:27 schrieb fvitalini:

> Thanks Frank for the comment. Feliks and I have been working on it 
> this afternoon. Can this be considered sufficient as an answer to the 
> reviewer so that we deal with these minor issues later? Of course it 
> will still need to be tested.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/pull/3#issuecomment-125654260.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fvitalini** [comment]
Yes I will check it tomorrow.

**Comment by franknoe** [comment]
Am 28/07/15 um 17:26 schrieb fvitalini:

> @ Frank:
> - psi /phi time series should be in degrees or radiants?
> 
> Good question. I would do this: Use a parameter radians=True in the 
> **init** of the Ramachandran basis set and the Ramachandran product 
> basis sets. Then in the calculation function you evaluate the input as 
> radians if radians=True, otherwise in degrees.
> - at the current status we treat the input files as bumpy array of
>   shape (T, X) with T = number of time steps and X= 2*number of
>   residues. Shouldn't this lead us to memory issues?
> 
> It could, but it's not the problem of this class to sort these issues 
> out. We could always read large trajectories in small chunks and feed 
> them to the basis set class. In EMMA it's done exactly like this, 
> because the exact same issue can appear with TICA (which is essentially 
> a variational approach). Doing this chunking is not something you need 
> to solve, because we have the infrastructure for a long-time solution.

As long as we have just residue basis sets the input is not really a 
problem anyway. Even for 100 residues and 1 million frames we would only 
have about one GB of memory, which is modest. A stronger problem can 
arises from the output of the basis set, because if you consider all 
product pairs with full excitation you can get an astronomic number of 
dimensions. At the moment we just have to keep it small.

>  *
> - I have sent you a pull request to add my commits (that I created
>   to branch in a fork at my name). Feliks instead had previously
>   created a branch directly from the original repository. What do
>   you prefer and can you check if the two of us have all the correct
>   permissions?
> 
> Pull request is perfect! But you can also create a branch in the main 
> repo and then make a pull request to the master branch. In the end it's 
> the same.
> 
> General question: how do we treat errors?
> 
> Are you talking about estimation errors in the timescales? You can still 
> do bootstrapping and feed the estimators in this package with the 
> bootstrapped trajectories.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/pull/3#issuecomment-125653872.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fvitalini** [comment]
Il giorno 28/lug/2015, alle ore 17:35, Frank Noe notifications@github.com ha scritto:

> Am 28/07/15 um 17:26 schrieb fvitalini:
> 
> > @ Frank:
> > - psi /phi time series should be in degrees or radiants?
> > 
> > Good question. I would do this: Use a parameter radians=True in the 
> > **init** of the Ramachandran basis set and the Ramachandran product 
> > basis sets. Then in the calculation function you evaluate the input as 
> > radians if radians=True, otherwise in degrees.

Ok I will include it, but I would use degrees as default as GROMACS output is in degrees.

> > - at the current status we treat the input files as bumpy array of
> >   shape (T, X) with T = number of time steps and X= 2*number of
> >   residues. Shouldn't this lead us to memory issues?
> > 
> > It could, but it's not the problem of this class to sort these issues 
> > out. We could always read large trajectories in small chunks and feed 
> > them to the basis set class. In EMMA it's done exactly like this, 
> > because the exact same issue can appear with TICA (which is essentially 
> > a variational approach). Doing this chunking is not something you need 
> > to solve, because we have the infrastructure for a long-time solution.

OK

> As long as we have just residue basis sets the input is not really a 
> problem anyway. Even for 100 residues and 1 million frames we would only 
> have about one GB of memory, which is modest. A stronger problem can 
> arises from the output of the basis set, because if you consider all 
> product pairs with full excitation you can get an astronomic number of 
> dimensions. At the moment we just have to keep it small.
> 
> > *
> > - I have sent you a pull request to add my commits (that I created
> >   to branch in a fork at my name). Feliks instead had previously
> >   created a branch directly from the original repository. What do
> >   you prefer and can you check if the two of us have all the correct
> >   permissions?
> > 
> > Pull request is perfect! But you can also create a branch in the main 
> > repo and then make a pull request to the master branch. In the end it's 
> > the same.
> > 
> > General question: how do we treat errors?
> > 
> > Are you talking about estimation errors in the timescales? You can still 
> > do bootstrapping and feed the estimators in this package with the 
> > bootstrapped trajectories.

No we intended numerical errors. For example GROMACS output sometimes gives angles of 180.00000001 that up to now I was manually setting back to 180. Is there an agreement on how to treat these errors?

**Comment by franknoe** [comment]
Am 28/07/15 um 18:26 schrieb fvitalini:

> Il giorno 28/lug/2015, alle ore 17:35, Frank Noe 
> notifications@github.com ha scritto:
> 
> > Am 28/07/15 um 17:26 schrieb fvitalini:
> > 
> > > @ Frank:
> > > - psi /phi time series should be in degrees or radiants?
> > > 
> > > Good question. I would do this: Use a parameter radians=True in the
> > > **init** of the Ramachandran basis set and the Ramachandran product
> > > basis sets. Then in the calculation function you evaluate the input as
> > > radians if radians=True, otherwise in degrees.
> 
> Ok I will include it, but I would use degrees as default as GROMACS 
> output is in degrees.
> But our package is not Gromacs-specific. In mdtraj, pyEMMA and numpy 
> radians are the default, so this is for future compatibility.
> 
> > > - at the current status we treat the input files as bumpy array of
> > >   shape (T, X) with T = number of time steps and X= 2*number of
> > >   residues. Shouldn't this lead us to memory issues?
> > > 
> > > It could, but it's not the problem of this class to sort these issues
> > > out. We could always read large trajectories in small chunks and feed
> > > them to the basis set class. In EMMA it's done exactly like this,
> > > because the exact same issue can appear with TICA (which is essentially
> > > a variational approach). Doing this chunking is not something you need
> > > to solve, because we have the infrastructure for a long-time solution.
> 
> OK
> 
> > As long as we have just residue basis sets the input is not really a
> > problem anyway. Even for 100 residues and 1 million frames we would 
> > only
> > have about one GB of memory, which is modest. A stronger problem can
> > arises from the output of the basis set, because if you consider all
> > product pairs with full excitation you can get an astronomic number of
> > dimensions. At the moment we just have to keep it small.
> > 
> > > *
> > > - I have sent you a pull request to add my commits (that I created
> > >   to branch in a fork at my name). Feliks instead had previously
> > >   created a branch directly from the original repository. What do
> > >   you prefer and can you check if the two of us have all the correct
> > >   permissions?
> > > 
> > > Pull request is perfect! But you can also create a branch in the main
> > > repo and then make a pull request to the master branch. In the end it's
> > > the same.
> > > 
> > > General question: how do we treat errors?
> > > 
> > > Are you talking about estimation errors in the timescales? You can 
> > > still
> > > do bootstrapping and feed the estimators in this package with the
> > > bootstrapped trajectories.
> 
> No we intended numerical errors. For example GROMACS output sometimes 
> gives angles of 180.00000001 that up to now I was manually setting 
> back to 180. Is there an agreement on how to treat these errors?
> Ah. I think that's not a problem because the basis functions are 
> coarse-grained anyway. But I think you can not exclude that the input 
> goes over the +-180 degree boundary and you'd have to map it back. For 
> example you could get 540 degrees as an input. So something like ((X + 
> 180.0) % 360.0 - 180.0)
> 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > https://github.com/markovmodel/variational/pull/3#issuecomment-125653872.
> > 
> > ## 
> > 
> > ---
> > 
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> > 
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > 
> > ## Mail: Arnimallee 6, 14195 Berlin, Germany
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/pull/3#issuecomment-125670810.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fnueske** [comment]
Hey Frank,
the last question was also about general error handling. If we spot a 
potentially important error source, what is the best way to deal with it 
in your opinion? And what options does python offer for this?
Thanks!

Am 28.07.15 um 18:26 schrieb fvitalini:

**Comment by franknoe** [comment]
Am 28/07/15 um 23:08 schrieb Feliks Nüske:

> Hey Frank,
> the last question was also about general error handling. If we spot a
> potentially important error source, what is the best way to deal with it
> in your opinion? And what options does python offer for this?
> I still don't really understand the question. Is this about tests? A 
> standard approach is to do write unit-tests which run the API functions 
> or objects with defined inputs and then test if they get a defined 
> output. For example, if you have written a function `square(x)` you 
> can write a test that tests if `square(2) == 4`. There is a well 
> defined way to write these tests and they can be set up to be 
> automatically run every time you submit a pull request. That way you can 
> test if your code still works after you made changes.

The standard approach is to test all API functions, i.e. everything you 
want to expose to the user (which is usually much less than the total 
number of functions).

But I'm not sure if this is you question. Tomorrow, Fabian is back so 
you can also consult him about this.

> Thanks!
> 
> Am 28.07.15 um 18:26 schrieb fvitalini:
> 
> > Il giorno 28/lug/2015, alle ore 17:35, Frank Noe
> > notifications@github.com ha scritto:
> > 
> > > Am 28/07/15 um 17:26 schrieb fvitalini:
> > > 
> > > > @ Frank:
> > > > - psi /phi time series should be in degrees or radiants?
> > > > 
> > > > Good question. I would do this: Use a parameter radians=True in the
> > > > **init** of the Ramachandran basis set and the Ramachandran product
> > > > basis sets. Then in the calculation function you evaluate the input as
> > > > radians if radians=True, otherwise in degrees.
> > 
> > Ok I will include it, but I would use degrees as default as GROMACS
> > output is in degrees.
> > 
> > > > - at the current status we treat the input files as bumpy array of
> > > >   shape (T, X) with T = number of time steps and X= 2*number of
> > > >   residues. Shouldn't this lead us to memory issues?
> > > > 
> > > > It could, but it's not the problem of this class to sort these issues
> > > > out. We could always read large trajectories in small chunks and feed
> > > > them to the basis set class. In EMMA it's done exactly like this,
> > > > because the exact same issue can appear with TICA (which is 
> > > > essentially
> > > > a variational approach). Doing this chunking is not something you need
> > > > to solve, because we have the infrastructure for a long-time solution.
> > 
> > OK
> > 
> > > As long as we have just residue basis sets the input is not really a
> > > problem anyway. Even for 100 residues and 1 million frames we would
> > > only
> > > have about one GB of memory, which is modest. A stronger problem can
> > > arises from the output of the basis set, because if you consider all
> > > product pairs with full excitation you can get an astronomic number of
> > > dimensions. At the moment we just have to keep it small.
> > > 
> > > > *
> > > > - I have sent you a pull request to add my commits (that I created
> > > >   to branch in a fork at my name). Feliks instead had previously
> > > >   created a branch directly from the original repository. What do
> > > >   you prefer and can you check if the two of us have all the correct
> > > >   permissions?
> > > > 
> > > > Pull request is perfect! But you can also create a branch in the main
> > > > repo and then make a pull request to the master branch. In the end 
> > > > it's
> > > > the same.
> > > > 
> > > > General question: how do we treat errors?
> > > > 
> > > > Are you talking about estimation errors in the timescales? You can
> > > > still
> > > > do bootstrapping and feed the estimators in this package with the
> > > > bootstrapped trajectories.
> > 
> > No we intended numerical errors. For example GROMACS output sometimes
> > gives angles of 180.00000001 that up to now I was manually setting
> > back to 180. Is there an agreement on how to treat these errors?
> > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/markovmodel/variational/pull/3#issuecomment-125653872.
> > 
> > > ## 
> > > 
> > > ---
> > > 
> > > Prof. Dr. Frank Noe
> > > Head of Computational Molecular Biology group
> > > Freie Universitaet Berlin
> > > 
> > > Phone: (+49) (0)30 838 75354
> > > Web: research.franknoe.de
> > > 
> > > ## Mail: Arnimallee 6, 14195 Berlin, Germany
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/markovmodel/variational/pull/3#issuecomment-125670810.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/pull/3#issuecomment-125754464.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fnueske** [comment]
Hey, all of this is very good to know. My original question was about 
wrong inputs, however. For example, if someone passes an array of wrong 
dimensions to the map function of our basis function objects, etc. I'll 
talk to Fabian today.

Am 28.07.15 um 23:15 schrieb Frank Noe:

**Pull request merged**
