### PR TITLE
Enable Travis-CI testing (and fix follow up fix setup)

### PR DESCRIPTION
**Pull request by marscher**
Tests are currently failing on Python 2.7 with 

```
ERROR: test_WrongDimension (variational.estimators.tests.TestEstimator.TestEstimator)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/variational-0+untagged.46.gecb3aec-py2.7-linux-x86_64.egg/variational/estimators/tests/TestEstimator.py", line 42, in test_WrongDimension

    self.assertRaises(Exception, self.estimator.add(self.traj0[:,:-1]))

  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/variational-0+untagged.46.gecb3aec-py2.7-linux-x86_64.egg/variational/estimators/lagged_correlation.py", line 40, in add

    self.output_dimension))

Exception: Number of basis functions is incorrect.Got 10, expected 11.
```

### CODE REVIEW

**Comment by marscher** [comment]
And the codebase is not Python3 compatible (which is easy to add).

**Comment by marscher** [comment]
@fnueske Can you have a look at the test failure please?

**Comment by marscher** [comment]
Python3 failure: 

```
======================================================================
ERROR: test_WrongDimension (variational.estimators.tests.TestEstimator.TestEstimator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marscher/miniconda/envs/_test/lib/python3.4/site-packages/variational-0+untagged.42.g74ce608.dirty-py3.4-linux-x86_64.egg/variational/estimators/tests/TestEstimator.py", line 33, in setUp
    self.estimator.add(self.traj0)
  File "/home/marscher/miniconda/envs/_test/lib/python3.4/site-packages/variational-0+untagged.42.g74ce608.dirty-py3.4-linux-x86_64.egg/variational/estimators/lagged_correlation.py", line 44, in add
    if X.shape <= self.tau:
TypeError: unorderable types: tuple() <= int()
```

**Comment by franknoe** [comment]
Oh, we haven't done anything for Python 3 yet in this package. I think 
we would first need to learn how to do that.

Am 19/11/15 um 14:21 schrieb Martin K. Scherer:

> Python3 failure:
> 
> |====================================================================== 
> ERROR: test_WrongDimension 
> 
> ## (variational.estimators.tests.TestEstimator.TestEstimator) 
> 
> Traceback (most recent call last): File 
> "/home/marscher/miniconda/envs/_test/lib/python3.4/site-packages/variational-0+untagged.42.g74ce608.dirty-py3.4-linux-x86_64.egg/variational/estimators/tests/TestEstimator.py", 
> line 33, in setUp self.estimator.add(self.traj0) File 
> "/home/marscher/miniconda/envs/_test/lib/python3.4/site-packages/variational-0+untagged.42.g74ce608.dirty-py3.4-linux-x86_64.egg/variational/estimators/lagged_correlation.py", 
> line 44, in add if X.shape <= self.tau: TypeError: unorderable types: 
> tuple() <= int() |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/pull/17#issuecomment-158055126.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
